<?php

return [
    'ariika' => [
        'base_url' => 'https://ariika.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'ARIIKA-',
        'parent_category' => [
            'name' => 'أثاث',
            'slug' => 'athath',
        ],
        'furniture_collections' => [
            'indoor-furniture' => 'الأثاث الداخلي',
            'furniture-1' => 'الأثاث',
            'living-room-1' => 'غرف المعيشة',
            'indoor-sofas' => 'الأرائك المنزلية',
            'bedroom' => 'أثاث غرف نوم',
            'dining-room' => 'غرف السفرة',
            'coffee-tables' => 'ترابيزات القهوة',
            'outdoor-1' => 'أثاث خارجي',
        ],
    ],

    'sedar' => [
        'base_url' => 'https://www.sedarglobal.com/egy-ar',
        'uploads_base' => 'https://api.sedarglobal.com/uploads/100001',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'SEDAR-',
        'parent_category' => [
            'name' => 'منسوجات',
            'slug' => 'textiles',
        ],
        'collections' => [
            'curtains-and-drapes' => 'الستائر — الكل',
            'fabric-curtain-pinch-pleat' => 'ستائر بينش بليت',
            'fabric-curtain-ripple-fold' => 'ستائر ويفي',
            'blackout-curtains' => 'ستائر بلاك آوت',
            'sheer-curtains' => 'ستائر شيفون',
        ],
    ],

    'gemma' => [
        'api_url' => 'https://api.gemma.qpix.io',
        'shop_url' => 'https://www.gemma.com.eg',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'GEMMA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'wall-ceramic' => 'Gemma — سيراميك حائط',
            'floor-ceramic' => 'Gemma — سيراميك أرضيات',
            'glazed-porcelain-matt' => 'Gemma — بورسلين مطفأ',
            'glazed-porcelain-polished' => 'Gemma — بورسلين مصقول',
            'floor' => 'Gemma — أرضيات',
            'wall' => 'Gemma — حائط',
            'kitchen' => 'Gemma — مطبخ',
            'bathroom' => 'Gemma — حمام',
            'living' => 'Gemma — معيشة',
            'bedroom' => 'Gemma — غرف نوم',
            'outdoor' => 'Gemma — خارجي',
            'indoor' => 'Gemma — داخلي',
        ],
        'collection_params' => [
            'wall-ceramic' => ['type' => '5b38e26262f1190f29f951e4'],
            'floor-ceramic' => ['type' => '5b38e26262f1190f29f951e8'],
            'glazed-porcelain-matt' => ['type' => '5b38e26262f1190f29f951e5'],
            'glazed-porcelain-polished' => ['type' => '5b38e26262f1190f29f951ec'],
            'floor' => ['type' => '5b61afd6b9b6e33aeffe7cc6'],
            'wall' => ['type' => '5b61afd2b9b6e33aeffe7cc5'],
            'kitchen' => ['rooms' => '5ae1e704cd292d2a900dfb93'],
            'bathroom' => ['rooms' => '5b61c7521c343e62779be068'],
            'living' => ['rooms' => '5ae1e71ecd292d2a900dfb94'],
            'bedroom' => ['rooms' => '5ae1e723cd292d2a900dfb95'],
            'outdoor' => ['rooms' => '5b623fcdd9816d5492d82bc8'],
            'indoor' => ['rooms' => '5b623fc9d9816d5492d82bc7'],
        ],
    ],

    'hans' => [
        'base_url' => 'https://hansegypt.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'HANS-',
        'parent_category' => [
            'name' => 'إكسسوارات',
            'slug' => 'accessories',
        ],
        'collections' => [
            'sinks' => 'HANS — مصارف',
            'ovens' => 'HANS — أفران',
        ],
    ],

    'cleopatra' => [
        'store_url' => 'https://www.cleopatraceramics.store',
        'catalog_url' => 'https://www.cleopatraceramics.com/ar',
        'api_url' => 'https://www.cleopatraceramics.store/wp-json/cleopatra-api/v1',
        'wc_store_url' => 'https://www.cleopatraceramics.store/wp-json/wc/store/v1',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'CLEOPATRA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'floor' => 'Cleopatra — أرضيات',
            'wall' => 'Cleopatra — حائط',
            'floor-and-wall' => 'Cleopatra — أرضيات وحوائط',
            'decor' => 'Cleopatra — ديكور',
            'marble-look' => 'Cleopatra — مظهر رخام',
            'wood-look' => 'Cleopatra — مظهر خشب',
            'stone-look' => 'Cleopatra — مظهر حجر',
            'carrara' => 'Cleopatra — Carrara',
            'leaf' => 'Cleopatra — Leaf',
        ],
        'collection_params' => [
            'floor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 614],
            'wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 615],
            'floor-and-wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 616],
            'decor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 618],
            'marble-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 25],
            'wood-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 26],
            'stone-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 27],
            'carrara' => ['collection_id' => 30723],
            'leaf' => ['collection_id' => 29379],
        ],
    ],
];
