<?php

return [
    'ariika' => [
        'base_url' => 'https://ariika.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'ARIIKA-',
        'parent_category' => [
            'name' => 'أثاث',
            'slug' => 'athath',
        ],
        'furniture_collections' => [
            'indoor-furniture' => 'الأثاث الداخلي',
            'furniture-1' => 'الأثاث',
            'living-room-1' => 'غرف المعيشة',
            'indoor-sofas' => 'الأرائك المنزلية',
            'bedroom' => 'أثاث غرف نوم',
            'dining-room' => 'غرف السفرة',
            'coffee-tables' => 'ترابيزات القهوة',
            'outdoor-1' => 'أثاث خارجي',
        ],
    ],

    'sedar' => [
        'base_url' => 'https://www.sedarglobal.com/egy-ar',
        'uploads_base' => 'https://api.sedarglobal.com/uploads/100001',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'SEDAR-',
        'parent_category' => [
            'name' => 'منسوجات',
            'slug' => 'textiles',
        ],
        'collections' => [
            'curtains-and-drapes' => 'الستائر — الكل',
            'fabric-curtain-pinch-pleat' => 'ستائر بينش بليت',
            'fabric-curtain-ripple-fold' => 'ستائر ويفي',
            'blackout-curtains' => 'ستائر بلاك آوت',
            'sheer-curtains' => 'ستائر شيفون',
        ],
    ],

    'gemma' => [
        'api_url' => 'https://api.gemma.qpix.io',
        'shop_url' => 'https://www.gemma.com.eg',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'GEMMA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'wall-ceramic' => 'Gemma — سيراميك حائط',
            'floor-ceramic' => 'Gemma — سيراميك أرضيات',
            'glazed-porcelain-matt' => 'Gemma — بورسلين مطفأ',
            'glazed-porcelain-polished' => 'Gemma — بورسلين مصقول',
            'floor' => 'Gemma — أرضيات',
            'wall' => 'Gemma — حائط',
            'kitchen' => 'Gemma — مطبخ',
            'bathroom' => 'Gemma — حمام',
            'living' => 'Gemma — معيشة',
            'bedroom' => 'Gemma — غرف نوم',
            'outdoor' => 'Gemma — خارجي',
            'indoor' => 'Gemma — داخلي',
        ],
        'collection_params' => [
            'wall-ceramic' => ['type' => '5b38e26262f1190f29f951e4'],
            'floor-ceramic' => ['type' => '5b38e26262f1190f29f951e8'],
            'glazed-porcelain-matt' => ['type' => '5b38e26262f1190f29f951e5'],
            'glazed-porcelain-polished' => ['type' => '5b38e26262f1190f29f951ec'],
            'floor' => ['type' => '5b61afd6b9b6e33aeffe7cc6'],
            'wall' => ['type' => '5b61afd2b9b6e33aeffe7cc5'],
            'kitchen' => ['rooms' => '5ae1e704cd292d2a900dfb93'],
            'bathroom' => ['rooms' => '5b61c7521c343e62779be068'],
            'living' => ['rooms' => '5ae1e71ecd292d2a900dfb94'],
            'bedroom' => ['rooms' => '5ae1e723cd292d2a900dfb95'],
            'outdoor' => ['rooms' => '5b623fcdd9816d5492d82bc8'],
            'indoor' => ['rooms' => '5b623fc9d9816d5492d82bc7'],
        ],
    ],

    'hans' => [
        'base_url' => 'https://hansegypt.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'HANS-',
        'parent_category' => [
            'name' => 'إكسسوارات',
            'slug' => 'accessories',
        ],
        'collections' => [
            'sinks' => 'HANS — مصارف',
            'ovens' => 'HANS — أفران',
        ],
    ],

    'cleopatra' => [
        'store_url' => 'https://www.cleopatraceramics.store',
        'catalog_url' => 'https://www.cleopatraceramics.com/ar',
        'api_url' => 'https://www.cleopatraceramics.store/wp-json/cleopatra-api/v1',
        'wc_store_url' => 'https://www.cleopatraceramics.store/wp-json/wc/store/v1',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'CLEOPATRA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'floor' => 'Cleopatra — أرضيات',
            'wall' => 'Cleopatra — حائط',
            'floor-and-wall' => 'Cleopatra — أرضيات وحوائط',
            'decor' => 'Cleopatra — ديكور',
            'marble-look' => 'Cleopatra — مظهر رخام',
            'wood-look' => 'Cleopatra — مظهر خشب',
            'stone-look' => 'Cleopatra — مظهر حجر',
            'carrara' => 'Cleopatra — Carrara',
            'leaf' => 'Cleopatra — Leaf',
        ],
        'collection_params' => [
            'floor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 614],
            'wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 615],
            'floor-and-wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 616],
            'decor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 618],
            'marble-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 25],
            'wood-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 26],
            'stone-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 27],
            'carrara' => ['collection_id' => 30723],
            'leaf' => ['collection_id' => 29379],
        ],
    ],

    'mahgoub' => [
        'base_url' => 'https://www.mahgoub.com',
        'grid_url' => 'https://www.mahgoub.com/on/demandware.store/Sites-mahgoub-Site/ar_EG/Search-UpdateGrid',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'MAHGOUB-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'parent_categories' => [
            'ceramics' => [
                'name' => 'سيراميك',
                'slug' => 'ceramics',
            ],
            'sanitary' => [
                'name' => 'صحي',
                'slug' => 'sanitary',
            ],
        ],
        'collections' => [
            'all' => 'Mahgoub — سيراميك و بورسلين',
            'imported' => 'Mahgoub — المستورد',
            'local' => 'Mahgoub — المحلي',
            'brand-aljohra' => 'Mahgoub — الجوهرة',
            'brand-porcelainosa' => 'Mahgoub — بورسالينوزا',
            'brand-grespania' => 'Mahgoub — جرسبانيا',
            'brand-rako' => 'Mahgoub — راك',
            'brand-ceifi' => 'Mahgoub — سيفري',
            'brand-spain' => 'Mahgoub — صنع في إسبانيا',
            'floor-porcelain' => 'Mahgoub — بورسلين أرضيات',
            'wall-porcelain' => 'Mahgoub — بورسلين حوائط',
            'floor-ceramic' => 'Mahgoub — سيراميك أرضيات',
            'wall-ceramic' => 'Mahgoub — سيراميك حوائط',
            'sanitary-all' => 'Mahgoub — صحي ووحدات',
            'sanitary-fixtures' => 'Mahgoub — أدوات صحية',
            'sanitary-concealed-tanks' => 'Mahgoub — خزانات دفن',
            'sanitary-units' => 'Mahgoub — وحدات',
            'sanitary-brand-ideal-standard' => 'Mahgoub — ايديال ستاندرد',
            'sanitary-brand-grohe' => 'Mahgoub — جروهي',
            'sanitary-brand-roca' => 'Mahgoub — روكا',
            'sanitary-brand-duravit' => 'Mahgoub — ديورافيت',
            'sanitary-brand-geberit' => 'Mahgoub — جيبرت',
            'sanitary-brand-hansgrohe' => 'Mahgoub — هانز جروهي',
            'sanitary-brand-whitehall' => 'Mahgoub — وايت فيل',
            'sanitary-type-toilet' => 'Mahgoub — مرحاض',
            'sanitary-type-wall-toilet' => 'Mahgoub — مرحاض معلق',
            'sanitary-type-basin' => 'Mahgoub — حوض',
            'sanitary-type-bidet' => 'Mahgoub — بيديه',
            'sanitary-type-urinal' => 'Mahgoub — مبولة',
            'sanitary-type-unit' => 'Mahgoub — وحدة',
            'sanitary-type-in-wall-tank' => 'Mahgoub — خزان دفن (نوع)',
            'sanitary-type-seat' => 'Mahgoub — سيديلى',
        ],
        'collection_parents' => [
            'all' => 'ceramics',
            'imported' => 'ceramics',
            'local' => 'ceramics',
            'brand-aljohra' => 'ceramics',
            'brand-porcelainosa' => 'ceramics',
            'brand-grespania' => 'ceramics',
            'brand-rako' => 'ceramics',
            'brand-ceifi' => 'ceramics',
            'brand-spain' => 'ceramics',
            'floor-porcelain' => 'ceramics',
            'wall-porcelain' => 'ceramics',
            'floor-ceramic' => 'ceramics',
            'wall-ceramic' => 'ceramics',
            'sanitary-all' => 'sanitary',
            'sanitary-fixtures' => 'sanitary',
            'sanitary-concealed-tanks' => 'sanitary',
            'sanitary-units' => 'sanitary',
            'sanitary-brand-ideal-standard' => 'sanitary',
            'sanitary-brand-grohe' => 'sanitary',
            'sanitary-brand-roca' => 'sanitary',
            'sanitary-brand-duravit' => 'sanitary',
            'sanitary-brand-geberit' => 'sanitary',
            'sanitary-brand-hansgrohe' => 'sanitary',
            'sanitary-brand-whitehall' => 'sanitary',
            'sanitary-type-toilet' => 'sanitary',
            'sanitary-type-wall-toilet' => 'sanitary',
            'sanitary-type-basin' => 'sanitary',
            'sanitary-type-bidet' => 'sanitary',
            'sanitary-type-urinal' => 'sanitary',
            'sanitary-type-unit' => 'sanitary',
            'sanitary-type-in-wall-tank' => 'sanitary',
            'sanitary-type-seat' => 'sanitary',
        ],
        'collection_params' => [
            'all' => ['cgid' => 'a0Y4K000003uF2jUAE'],
            'imported' => ['cgid' => 'a0Y4K000003uF2jUAE-a0Y4K000003uF39UAE'],
            'local' => ['cgid' => 'a0Y4K000003uF2jUAE-a0Y4K000003uF3HUAU'],
            'brand-aljohra' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'الجوهرة'],
            'brand-porcelainosa' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'بورسالينوزا '],
            'brand-grespania' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جرسبانيا'],
            'brand-rako' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'راك'],
            'brand-ceifi' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'سيفري'],
            'brand-spain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'صنع في إسبانيا'],
            'floor-porcelain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Floor Porcelain'],
            'wall-porcelain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Porcelain'],
            'floor-ceramic' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Floor Ceramic'],
            'wall-ceramic' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Ceramic'],
            'sanitary-all' => ['cgid' => 'a0Y4K000003uF2eUAE'],
            'sanitary-fixtures' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF7rUAE'],
            'sanitary-concealed-tanks' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF2tUAE'],
            'sanitary-units' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF7wUAE'],
            'sanitary-brand-ideal-standard' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'ايديال ستاندرد'],
            'sanitary-brand-grohe' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جروهي'],
            'sanitary-brand-roca' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'روكا'],
            'sanitary-brand-duravit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'ديورافيت'],
            'sanitary-brand-geberit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جيبرت'],
            'sanitary-brand-hansgrohe' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'هانز جروهي'],
            'sanitary-brand-whitehall' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'وايت فيل'],
            'sanitary-type-toilet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Toilet'],
            'sanitary-type-wall-toilet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Mounted Toilet'],
            'sanitary-type-basin' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Basin'],
            'sanitary-type-bidet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Bidet'],
            'sanitary-type-urinal' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Urinal'],
            'sanitary-type-unit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Unit'],
            'sanitary-type-in-wall-tank' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'In Wall Flush Tank'],
            'sanitary-type-seat' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Cover Seat'],
        ],
    ],

    'sallab' => [
        'base_url' => 'https://www.ahmedelsallab.com',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'SALLAB-',
        'parent_category' => [
            'name' => 'الأجهزة المنزلية',
            'slug' => 'home-appliances',
        ],
        'collections' => [
            'all' => 'Sallab — الأجهزة المنزلية',
            'air-conditioners' => 'Sallab — مكيفات',
            'fridges' => 'Sallab — ثلاجات',
            'washing-machines' => 'Sallab — غسالات',
            'deep-freezer' => 'Sallab — ديب فريزر',
            'ovens-cookers' => 'Sallab — أفران وبوتاجازات',
            'water-heaters' => 'Sallab — سخانات مياه',
            'dishwasher' => 'Sallab — غسالات أطباق',
            'televisions' => 'Sallab — تلفزيونات',
            'food-processors' => 'Sallab — محضرات طعام',
            'vacuum' => 'Sallab — مكانس كهربائية',
            'kettle' => 'Sallab — غلايات',
            'microwave' => 'Sallab — ميكروويف',
            'irons-and-steamers' => 'Sallab — مكاوي',
            'water-dispensers' => 'Sallab — برادات مياه',
            'water-filters' => 'Sallab — فلاتر مياه',
            'fans' => 'Sallab — مراوح',
            'hoods-exhaust-fans' => 'Sallab — شفاطات ومراوح',
            'electric-radiator' => 'Sallab — دفايات',
            'large-home-appliances' => 'Sallab — أجهزة كبيرة',
            'small-home-appliances' => 'Sallab — أجهزة صغيرة',
        ],
        'collection_params' => [
            'all' => ['path' => '/en/home-appliances.html'],
            'air-conditioners' => ['path' => '/en/home-appliances/air-conditioners.html'],
            'fridges' => ['path' => '/en/home-appliances/large-home-appliances/fridges.html'],
            'washing-machines' => ['path' => '/en/home-appliances/large-home-appliances/washing-machines.html'],
            'deep-freezer' => ['path' => '/en/home-appliances/large-home-appliances/deep-freezer.html'],
            'ovens-cookers' => ['path' => '/en/home-appliances/large-home-appliances/ovens-cookers.html'],
            'water-heaters' => ['path' => '/en/home-appliances/large-home-appliances/water-heaters.html'],
            'dishwasher' => ['path' => '/en/home-appliances/large-home-appliances/dishwasher.html'],
            'televisions' => ['path' => '/en/home-appliances/televisions.html'],
            'food-processors' => ['path' => '/en/home-appliances/small-home-applainces/food-processors.html'],
            'vacuum' => ['path' => '/en/home-appliances/small-home-applainces/vacuum.html'],
            'kettle' => ['path' => '/en/home-appliances/small-home-applainces/kettle.html'],
            'microwave' => ['path' => '/en/home-appliances/small-home-applainces/microwave.html'],
            'irons-and-steamers' => ['path' => '/en/home-appliances/small-home-applainces/irons-and-steamers.html'],
            'water-dispensers' => ['path' => '/en/home-appliances/small-home-applainces/water-dispensers.html'],
            'water-filters' => ['path' => '/en/home-appliances/small-home-applainces/water-filters.html'],
            'fans' => ['path' => '/en/home-appliances/small-home-applainces/fans.html'],
            'hoods-exhaust-fans' => ['path' => '/en/home-appliances/small-home-applainces/hoods-exhaust-fans.html'],
            'electric-radiator' => ['path' => '/en/home-appliances/small-home-applainces/electric-radiator.html'],
            'large-home-appliances' => ['path' => '/en/home-appliances/large-home-appliances.html'],
            'small-home-appliances' => ['path' => '/en/home-appliances/small-home-applainces.html'],
        ],
    ],

    'raya' => [
        'graphql_url' => 'https://api-rayashop.global.ssl.fastly.net/graphql',
        'shop_url' => 'https://www.rayashop.com/ar',
        'store_code' => 'ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 800,
        'sku_prefix' => 'RAYA-',
        'parent_category' => [
            'name' => 'الأجهزة المنزلية',
            'slug' => 'home-appliances',
        ],
        'collections' => [
            'all' => 'الأجهزة المنزلية',
            'refrigerators' => 'ثلاجات',
            'washing-machines' => 'غسالات ملابس',
            'air-conditioners' => 'تكييفات',
            'cookers' => 'بوتاجازات',
            'freezers' => 'فريزر',
            'dishwashers' => 'غسالات أطباق',
            'water-heaters' => 'سخانات',
            'air-cooler' => 'مبرد هواء صحراوي',
            'small-appliances' => 'أجهزة صغيرة',
            'kitchen-appliances' => 'أجهزة مطبخ',
            'televisions' => 'تلفزيونات',
        ],
        'collection_params' => [
            'all' => ['url_key' => 'large-appliances'],
            'refrigerators' => ['url_key' => 'refrigerators'],
            'washing-machines' => ['url_key' => 'washing-machines'],
            'air-conditioners' => ['url_key' => 'air-conditioners'],
            'cookers' => ['url_key' => 'cookers'],
            'freezers' => ['url_key' => 'freezers'],
            'dishwashers' => ['url_key' => 'dishwashers'],
            'water-heaters' => ['url_key' => 'water-heaters'],
            'air-cooler' => ['url_key' => 'air-cooler'],
            'small-appliances' => ['url_key' => 'small-appliances'],
            'kitchen-appliances' => ['url_key' => 'kitchen-appliances'],
            'televisions' => ['url_key' => 'televisions'],
        ],
    ],
];
