<?php

return [
    'ariika' => [
        'base_url' => 'https://ariika.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'ARIIKA-',
        'parent_category' => [
            'name' => 'أثاث',
            'slug' => 'athath',
        ],
        'furniture_collections' => [
            'indoor-furniture' => 'الأثاث الداخلي',
            'furniture-1' => 'الأثاث',
            'living-room-1' => 'غرف المعيشة',
            'indoor-sofas' => 'الأرائك المنزلية',
            'bedroom' => 'أثاث غرف نوم',
            'dining-room' => 'غرف السفرة',
            'coffee-tables' => 'ترابيزات القهوة',
            'outdoor-1' => 'أثاث خارجي',
        ],
    ],

    'sedar' => [
        'base_url' => 'https://www.sedarglobal.com/egy-ar',
        'uploads_base' => 'https://api.sedarglobal.com/uploads/100001',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'SEDAR-',
        'parent_category' => [
            'name' => 'منسوجات',
            'slug' => 'textiles',
        ],
        'collections' => [
            'curtains-and-drapes' => 'الستائر — الكل',
            'fabric-curtain-pinch-pleat' => 'ستائر بينش بليت',
            'fabric-curtain-ripple-fold' => 'ستائر ويفي',
            'blackout-curtains' => 'ستائر بلاك آوت',
            'sheer-curtains' => 'ستائر شيفون',
        ],
    ],

    'gemma' => [
        'api_url' => 'https://api.gemma.qpix.io',
        'shop_url' => 'https://www.gemma.com.eg',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'GEMMA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'wall-ceramic' => 'سيراميك حائط',
            'floor-ceramic' => 'سيراميك أرضيات',
            'glazed-porcelain-matt' => 'بورسلين مطفأ',
            'glazed-porcelain-polished' => 'بورسلين مصقول',
            'floor' => 'أرضيات',
            'wall' => 'حائط',
            'kitchen' => 'مطبخ',
            'bathroom' => 'حمام',
            'living' => 'معيشة',
            'bedroom' => 'غرف نوم',
            'outdoor' => 'خارجي',
            'indoor' => 'داخلي',
        ],
        'collection_params' => [
            'wall-ceramic' => ['type' => '5b38e26262f1190f29f951e4'],
            'floor-ceramic' => ['type' => '5b38e26262f1190f29f951e8'],
            'glazed-porcelain-matt' => ['type' => '5b38e26262f1190f29f951e5'],
            'glazed-porcelain-polished' => ['type' => '5b38e26262f1190f29f951ec'],
            'floor' => ['type' => '5b61afd6b9b6e33aeffe7cc6'],
            'wall' => ['type' => '5b61afd2b9b6e33aeffe7cc5'],
            'kitchen' => ['rooms' => '5ae1e704cd292d2a900dfb93'],
            'bathroom' => ['rooms' => '5b61c7521c343e62779be068'],
            'living' => ['rooms' => '5ae1e71ecd292d2a900dfb94'],
            'bedroom' => ['rooms' => '5ae1e723cd292d2a900dfb95'],
            'outdoor' => ['rooms' => '5b623fcdd9816d5492d82bc8'],
            'indoor' => ['rooms' => '5b623fc9d9816d5492d82bc7'],
        ],
    ],

    'hans' => [
        'base_url' => 'https://hansegypt.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 500,
        'sku_prefix' => 'HANS-',
        'parent_category' => [
            'name' => 'إكسسوارات',
            'slug' => 'accessories',
        ],
        'collections' => [
            'sinks' => 'HANS — مصارف',
            'ovens' => 'HANS — أفران',
        ],
    ],

    'cleopatra' => [
        'store_url' => 'https://www.cleopatraceramics.store',
        'catalog_url' => 'https://www.cleopatraceramics.com/ar',
        'api_url' => 'https://www.cleopatraceramics.store/wp-json/cleopatra-api/v1',
        'wc_store_url' => 'https://www.cleopatraceramics.store/wp-json/wc/store/v1',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'CLEOPATRA-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'collections' => [
            'floor' => 'أرضيات',
            'wall' => 'حائط',
            'floor-and-wall' => 'أرضيات وحوائط',
            'decor' => 'ديكور',
            'marble-look' => 'مظهر رخام',
            'wood-look' => 'مظهر خشب',
            'stone-look' => 'مظهر حجر',
            'carrara' => 'Carrara',
            'leaf' => 'Leaf',
        ],
        'collection_params' => [
            'floor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 614],
            'wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 615],
            'floor-and-wall' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 616],
            'decor' => ['taxonomy' => 'clp_product_type_tax', 'term_id' => 618],
            'marble-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 25],
            'wood-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 26],
            'stone-look' => ['taxonomy' => 'clp_collection_look_tax', 'term_id' => 27],
            'carrara' => ['collection_id' => 30723],
            'leaf' => ['collection_id' => 29379],
        ],
    ],

    'mahgoub' => [
        'base_url' => 'https://www.mahgoub.com',
        'grid_url' => 'https://www.mahgoub.com/on/demandware.store/Sites-mahgoub-Site/ar_EG/Search-UpdateGrid',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'MAHGOUB-',
        'parent_category' => [
            'name' => 'سيراميك',
            'slug' => 'ceramics',
        ],
        'parent_categories' => [
            'ceramics' => [
                'name' => 'سيراميك',
                'slug' => 'ceramics',
            ],
            'sanitary' => [
                'name' => 'صحي',
                'slug' => 'sanitary',
            ],
        ],
        'collections' => [
            'all' => 'سيراميك و بورسلين',
            'imported' => 'المستورد',
            'local' => 'المحلي',
            'brand-aljohra' => 'الجوهرة',
            'brand-porcelainosa' => 'بورسالينوزا',
            'brand-grespania' => 'جرسبانيا',
            'brand-rako' => 'راك',
            'brand-ceifi' => 'سيفري',
            'brand-spain' => 'صنع في إسبانيا',
            'floor-porcelain' => 'بورسلين أرضيات',
            'wall-porcelain' => 'بورسلين حوائط',
            'floor-ceramic' => 'سيراميك أرضيات',
            'wall-ceramic' => 'سيراميك حوائط',
            'sanitary-all' => 'صحي ووحدات',
            'sanitary-fixtures' => 'أدوات صحية',
            'sanitary-concealed-tanks' => 'خزانات دفن',
            'sanitary-units' => 'وحدات',
            'sanitary-brand-ideal-standard' => 'ايديال ستاندرد',
            'sanitary-brand-grohe' => 'جروهي',
            'sanitary-brand-roca' => 'روكا',
            'sanitary-brand-duravit' => 'ديورافيت',
            'sanitary-brand-geberit' => 'جيبرت',
            'sanitary-brand-hansgrohe' => 'هانز جروهي',
            'sanitary-brand-whitehall' => 'وايت فيل',
            'sanitary-type-toilet' => 'مرحاض',
            'sanitary-type-wall-toilet' => 'مرحاض معلق',
            'sanitary-type-basin' => 'حوض',
            'sanitary-type-bidet' => 'بيديه',
            'sanitary-type-urinal' => 'مبولة',
            'sanitary-type-unit' => 'وحدة',
            'sanitary-type-in-wall-tank' => 'خزان دفن',
            'sanitary-type-seat' => 'سيديلى',
        ],
        'collection_parents' => [
            'all' => 'ceramics',
            'imported' => 'ceramics',
            'local' => 'ceramics',
            'brand-aljohra' => 'ceramics',
            'brand-porcelainosa' => 'ceramics',
            'brand-grespania' => 'ceramics',
            'brand-rako' => 'ceramics',
            'brand-ceifi' => 'ceramics',
            'brand-spain' => 'ceramics',
            'floor-porcelain' => 'ceramics',
            'wall-porcelain' => 'ceramics',
            'floor-ceramic' => 'ceramics',
            'wall-ceramic' => 'ceramics',
            'sanitary-all' => 'sanitary',
            'sanitary-fixtures' => 'sanitary',
            'sanitary-concealed-tanks' => 'sanitary',
            'sanitary-units' => 'sanitary',
            'sanitary-brand-ideal-standard' => 'sanitary',
            'sanitary-brand-grohe' => 'sanitary',
            'sanitary-brand-roca' => 'sanitary',
            'sanitary-brand-duravit' => 'sanitary',
            'sanitary-brand-geberit' => 'sanitary',
            'sanitary-brand-hansgrohe' => 'sanitary',
            'sanitary-brand-whitehall' => 'sanitary',
            'sanitary-type-toilet' => 'sanitary',
            'sanitary-type-wall-toilet' => 'sanitary',
            'sanitary-type-basin' => 'sanitary',
            'sanitary-type-bidet' => 'sanitary',
            'sanitary-type-urinal' => 'sanitary',
            'sanitary-type-unit' => 'sanitary',
            'sanitary-type-in-wall-tank' => 'sanitary',
            'sanitary-type-seat' => 'sanitary',
        ],
        'collection_params' => [
            'all' => ['cgid' => 'a0Y4K000003uF2jUAE', 'category_slug' => 'all'],
            'imported' => ['cgid' => 'a0Y4K000003uF2jUAE-a0Y4K000003uF39UAE', 'category_slug' => 'imported'],
            'local' => ['cgid' => 'a0Y4K000003uF2jUAE-a0Y4K000003uF3HUAU', 'category_slug' => 'local'],
            'brand-aljohra' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'الجوهرة', 'category_slug' => 'brand-aljohra'],
            'brand-porcelainosa' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'بورسالينوزا ', 'category_slug' => 'brand-porcelainosa'],
            'brand-grespania' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جرسبانيا', 'category_slug' => 'brand-grespania'],
            'brand-rako' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'راك', 'category_slug' => 'brand-rako'],
            'brand-ceifi' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'سيفري', 'category_slug' => 'brand-ceifi'],
            'brand-spain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'merchandise', 'prefv1' => 'صنع في إسبانيا', 'category_slug' => 'brand-spain'],
            'floor-porcelain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Floor Porcelain', 'category_slug' => 'floor-porcelain'],
            'wall-porcelain' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Porcelain', 'category_slug' => 'wall-porcelain'],
            'floor-ceramic' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Floor Ceramic', 'category_slug' => 'floor-ceramic'],
            'wall-ceramic' => ['cgid' => 'a0Y4K000003uF2jUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Ceramic', 'category_slug' => 'wall-ceramic'],
            'sanitary-all' => ['cgid' => 'a0Y4K000003uF2eUAE', 'category_slug' => 'sanitary-all'],
            'sanitary-fixtures' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF7rUAE', 'category_slug' => 'sanitary-fixtures'],
            'sanitary-concealed-tanks' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF2tUAE', 'category_slug' => 'sanitary-concealed-tanks'],
            'sanitary-units' => ['cgid' => 'a0Y4K000003uF2eUAE-a0Y4K000003uF7wUAE', 'category_slug' => 'sanitary-units'],
            'sanitary-brand-ideal-standard' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'ايديال ستاندرد', 'category_slug' => 'sanitary-brand-ideal-standard'],
            'sanitary-brand-grohe' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جروهي', 'category_slug' => 'sanitary-brand-grohe'],
            'sanitary-brand-roca' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'روكا', 'category_slug' => 'sanitary-brand-roca'],
            'sanitary-brand-duravit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'ديورافيت', 'category_slug' => 'sanitary-brand-duravit'],
            'sanitary-brand-geberit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'جيبرت', 'category_slug' => 'sanitary-brand-geberit'],
            'sanitary-brand-hansgrohe' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'هانز جروهي', 'category_slug' => 'sanitary-brand-hansgrohe'],
            'sanitary-brand-whitehall' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'merchandise', 'prefv1' => 'وايت فيل', 'category_slug' => 'sanitary-brand-whitehall'],
            'sanitary-type-toilet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Toilet', 'category_slug' => 'sanitary-type-toilet'],
            'sanitary-type-wall-toilet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Wall Mounted Toilet', 'category_slug' => 'sanitary-type-wall-toilet'],
            'sanitary-type-basin' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Basin', 'category_slug' => 'sanitary-type-basin'],
            'sanitary-type-bidet' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Bidet', 'category_slug' => 'sanitary-type-bidet'],
            'sanitary-type-urinal' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Urinal', 'category_slug' => 'sanitary-type-urinal'],
            'sanitary-type-unit' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Unit', 'category_slug' => 'sanitary-type-unit'],
            'sanitary-type-in-wall-tank' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'In Wall Flush Tank', 'category_slug' => 'sanitary-type-in-wall-tank'],
            'sanitary-type-seat' => ['cgid' => 'a0Y4K000003uF2eUAE', 'prefn1' => 'sort', 'prefv1' => 'Cover Seat', 'category_slug' => 'sanitary-type-seat'],
        ],
    ],

    'sallab' => [
        'base_url' => 'https://www.ahmedelsallab.com',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'SALLAB-',
        'parent_category' => [
            'name' => 'الأجهزة المنزلية',
            'slug' => 'home-appliances',
        ],
        'collections' => [
            'all' => 'أجهزة منزلية (متنوعة)',
            'air-conditioners' => 'تكييفات',
            'fridges' => 'ثلاجات',
            'washing-machines' => 'غسالات ملابس',
            'deep-freezer' => 'فريزر',
            'ovens-cookers' => 'بوتاجازات',
            'water-heaters' => 'سخانات',
            'dishwasher' => 'غسالات أطباق',
            'televisions' => 'تلفزيونات',
            'food-processors' => 'محضرات طعام',
            'vacuum' => 'مكانس كهربائية',
            'kettle' => 'غلايات',
            'microwave' => 'ميكروويف',
            'irons-and-steamers' => 'مكاوي',
            'water-dispensers' => 'برادات مياه',
            'water-filters' => 'فلاتر مياه',
            'fans' => 'مراوح',
            'hoods-exhaust-fans' => 'شفاطات ومراوح',
            'electric-radiator' => 'دفايات',
            'large-home-appliances' => 'أجهزة كبيرة',
            'small-home-appliances' => 'أجهزة صغيرة',
        ],
        'collection_params' => [
            'all' => ['path' => '/en/home-appliances.html', 'category_slug' => 'large-appliances'],
            'air-conditioners' => ['path' => '/en/home-appliances/air-conditioners.html', 'category_slug' => 'air-conditioners'],
            'fridges' => ['path' => '/en/home-appliances/large-home-appliances/fridges.html', 'category_slug' => 'refrigerators'],
            'washing-machines' => ['path' => '/en/home-appliances/large-home-appliances/washing-machines.html', 'category_slug' => 'washing-machines'],
            'deep-freezer' => ['path' => '/en/home-appliances/large-home-appliances/deep-freezer.html', 'category_slug' => 'freezers'],
            'ovens-cookers' => ['path' => '/en/home-appliances/large-home-appliances/ovens-cookers.html', 'category_slug' => 'cookers'],
            'water-heaters' => ['path' => '/en/home-appliances/large-home-appliances/water-heaters.html', 'category_slug' => 'water-heaters'],
            'dishwasher' => ['path' => '/en/home-appliances/large-home-appliances/dishwasher.html', 'category_slug' => 'dishwashers'],
            'televisions' => ['path' => '/en/home-appliances/televisions.html', 'category_slug' => 'televisions'],
            'food-processors' => ['path' => '/en/home-appliances/small-home-applainces/food-processors.html', 'category_slug' => 'food-processors'],
            'vacuum' => ['path' => '/en/home-appliances/small-home-applainces/vacuum.html', 'category_slug' => 'vacuum'],
            'kettle' => ['path' => '/en/home-appliances/small-home-applainces/kettle.html', 'category_slug' => 'kettle'],
            'microwave' => ['path' => '/en/home-appliances/small-home-applainces/microwave.html', 'category_slug' => 'microwave'],
            'irons-and-steamers' => ['path' => '/en/home-appliances/small-home-applainces/irons-and-steamers.html', 'category_slug' => 'irons-and-steamers'],
            'water-dispensers' => ['path' => '/en/home-appliances/small-home-applainces/water-dispensers.html', 'category_slug' => 'water-dispensers'],
            'water-filters' => ['path' => '/en/home-appliances/small-home-applainces/water-filters.html', 'category_slug' => 'water-filters'],
            'fans' => ['path' => '/en/home-appliances/small-home-applainces/fans.html', 'category_slug' => 'fans'],
            'hoods-exhaust-fans' => ['path' => '/en/home-appliances/small-home-applainces/hoods-exhaust-fans.html', 'category_slug' => 'hoods-exhaust-fans'],
            'electric-radiator' => ['path' => '/en/home-appliances/small-home-applainces/electric-radiator.html', 'category_slug' => 'electric-radiator'],
            'large-home-appliances' => ['path' => '/en/home-appliances/large-home-appliances.html', 'category_slug' => 'large-appliances'],
            'small-home-appliances' => ['path' => '/en/home-appliances/small-home-applainces.html', 'category_slug' => 'small-appliances'],
        ],
    ],

    'raya' => [
        'graphql_url' => 'https://api-rayashop.global.ssl.fastly.net/graphql',
        'shop_url' => 'https://www.rayashop.com/ar',
        'store_code' => 'ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 800,
        'sku_prefix' => 'RAYA-',
        'parent_category' => [
            'name' => 'الأجهزة المنزلية',
            'slug' => 'home-appliances',
        ],
        'collections' => [
            'all' => 'الأجهزة المنزلية',
            'refrigerators' => 'ثلاجات',
            'washing-machines' => 'غسالات ملابس',
            'air-conditioners' => 'تكييفات',
            'cookers' => 'بوتاجازات',
            'freezers' => 'فريزر',
            'dishwashers' => 'غسالات أطباق',
            'water-heaters' => 'سخانات',
            'air-cooler' => 'مبرد هواء صحراوي',
            'small-appliances' => 'أجهزة صغيرة',
            'kitchen-appliances' => 'أجهزة مطبخ',
            'televisions' => 'تلفزيونات',
        ],
        'collection_params' => [
            'all' => ['url_key' => 'large-appliances', 'category_slug' => 'large-appliances'],
            'refrigerators' => ['url_key' => 'refrigerators', 'category_slug' => 'refrigerators'],
            'washing-machines' => ['url_key' => 'washing-machines', 'category_slug' => 'washing-machines'],
            'air-conditioners' => ['url_key' => 'air-conditioners', 'category_slug' => 'air-conditioners'],
            'cookers' => ['url_key' => 'cookers', 'category_slug' => 'cookers'],
            'freezers' => ['url_key' => 'freezers', 'category_slug' => 'freezers'],
            'dishwashers' => ['url_key' => 'dishwashers', 'category_slug' => 'dishwashers'],
            'water-heaters' => ['url_key' => 'water-heaters', 'category_slug' => 'water-heaters'],
            'air-cooler' => ['url_key' => 'air-cooler', 'category_slug' => 'air-cooler'],
            'small-appliances' => ['url_key' => 'small-appliances', 'category_slug' => 'small-appliances'],
            'kitchen-appliances' => ['url_key' => 'kitchen-appliances', 'category_slug' => 'kitchen-appliances'],
            'televisions' => ['url_key' => 'televisions', 'category_slug' => 'televisions'],
        ],
    ],

    'shaheen' => [
        'wc_store_url' => 'https://shaheeneg.com/ar/wp-json/wc/store/v1',
        'shop_url' => 'https://shaheeneg.com/ar',
        'user_agent' => 'HomeBlendStore-ProductImporter/1.0',
        'connect_timeout' => 30,
        'request_timeout' => 90,
        'retry_times' => 3,
        'retry_sleep_ms' => 1500,
        'delay_ms' => 300,
        'sku_prefix' => 'SHAHEEN-',
        'parent_category' => [
            'name' => 'الأجهزة المنزلية',
            'slug' => 'home-appliances',
        ],
        'collections' => [
            'refrigerators' => 'ثلاجات',
            'freezers' => 'فريزر',
            'washing-machines' => 'غسالات ملابس',
            'air-conditioners' => 'تكييفات',
            'cookers' => 'بوتاجازات',
            'dishwashers' => 'غسالات أطباق',
            'water-heaters' => 'سخانات',
            'televisions' => 'تلفزيونات',
            'small-appliances' => 'أجهزة صغيرة',
            'kitchen-appliances' => 'أجهزة مطبخ',
            'food-processors' => 'محضرات طعام',
            'vacuum' => 'مكانس كهربائية',
            'microwave' => 'ميكروويف',
        ],
        'collection_params' => [
            'refrigerators' => ['category_id' => 80, 'category_slug' => 'refrigerators'],
            'freezers' => ['category_id' => 125, 'category_slug' => 'freezers'],
            'washing-machines' => ['category_id' => 55, 'category_slug' => 'washing-machines'],
            'air-conditioners' => ['category_id' => 65, 'category_slug' => 'air-conditioners'],
            'cookers' => ['category_id' => 111, 'category_slug' => 'cookers'],
            'dishwashers' => ['category_id' => 81, 'category_slug' => 'dishwashers'],
            'water-heaters' => ['category_id' => 148, 'category_slug' => 'water-heaters'],
            'televisions' => ['category_id' => 63, 'category_slug' => 'televisions'],
            'small-appliances' => ['category_id' => 64, 'category_slug' => 'small-appliances'],
            'kitchen-appliances' => ['category_id' => 143, 'category_slug' => 'kitchen-appliances'],
            'food-processors' => ['category_id' => 149, 'category_slug' => 'food-processors'],
            'vacuum' => ['category_id' => 161, 'category_slug' => 'vacuum'],
            'microwave' => ['category_id' => 160, 'category_slug' => 'microwave'],
        ],
    ],
];
